name: PowerShell script
author: Oleksandr Nikolaiev (rework microsoft AL-Go)
inputs:
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  remove_current:
    description: The GitHub actor running the action
    required: false
runs:
  using: composite
  steps:
    - run: 
            try { 
                if('${{ inputs.remove_current }}' -eq 'true')
                {
                    ${{ github.action_path }}/WorkflowPostProcess.ps1 -token '${{ inputs.token }}' -remove:$True
                }
                else
                {
                    ${{ github.action_path }}/WorkflowPostProcess.ps1 -token '${{ inputs.token }}'
                }
           } catch { 
                Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 
           }
      shell: PowerShell
branding:
  icon: terminal
  color: blue
