name: PowerShell script
author: Oleksandr Nikolaiev (rework microsoft AL-Go)
runs:
  using: composite
  steps:
    - run: try { ${{ github.action_path }}/WorkflowPostProcess.ps1 } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
      shell: PowerShell
branding:
  icon: terminal
  color: blue
